/* ================================================================
   FLY RESTAURANT — products-data.js
   Auto-generated master menu catalogue (all 76 items across every
   category). Used by the site-wide live search so a search result
   always deep-links to the REAL item card on the menu (via
   #item-<slug> anchor), instead of guessing or scrolling nowhere.

   veg field: "veg" | "nonveg" | "egg" — best-effort classification
   based on dish names. A few street-food items (Hamburger, Tacos,
   Pizza, Sandwich) had no explicit meat/veg wording, so a sensible
   default was chosen. Please double-check these before going live.

   rating / reviews: SAMPLE placeholder values (deterministic, not
   real customer data) so the UI has something to display. Replace
   with real review data once you start collecting it.

   bestseller: a small starter set of "Bestseller" tags — feel free
   to change which dishes are flagged.

   description: auto-generated marketing copy per dish (templated by
   category). Feel free to hand-write your own for a more personal
   touch — these are meant as a solid, professional starting point.
================================================================ */
const MENU_DB = [
  {
    "slug": "pasta-light",
    "name": "Pasta Light",
    "price": 80,
    "img": "assets/images/starters/Pasta Light.jpg",
    "category": "starters",
    "categoryLabel": "Starters",
    "veg": "veg",
    "rating": 4.8,
    "reviews": 144,
    "bestseller": false,
    "description": "Crispy, flavourful and irresistible — our Pasta Light is a guest favourite to kick off your meal."
  },
  {
    "slug": "veg-spring-rolls",
    "name": "Veg Spring Rolls",
    "price": 140,
    "img": "assets/images/starters/Veg Spring Rolls.jpg",
    "category": "starters",
    "categoryLabel": "Starters",
    "veg": "veg",
    "rating": 4.6,
    "reviews": 240,
    "bestseller": false,
    "description": "Crispy, flavourful and irresistible — our Veg Spring Rolls is a guest favourite to kick off your meal."
  },
  {
    "slug": "veg-paneer",
    "name": "Veg Paneer",
    "price": 110,
    "img": "assets/images/starters/Veg Paneer.jpg",
    "category": "starters",
    "categoryLabel": "Starters",
    "veg": "veg",
    "rating": 4.0,
    "reviews": 263,
    "bestseller": false,
    "description": "A perfect starter to awaken your appetite — Veg Paneer is prepared fresh with premium ingredients and served piping hot."
  },
  {
    "slug": "paneer-tikka",
    "name": "Paneer Tikka",
    "price": 120,
    "img": "assets/images/starters/paneer-tikka.jpg",
    "category": "starters",
    "categoryLabel": "Starters",
    "veg": "veg",
    "rating": 4.2,
    "reviews": 55,
    "bestseller": true,
    "description": "A perfect starter to awaken your appetite — Paneer Tikka is prepared fresh with premium ingredients and served piping hot."
  },
  {
    "slug": "crispy-vegetable-cutlets",
    "name": "Crispy Vegetable Cutlets",
    "price": 150,
    "img": "assets/images/starters/Crispy Vegetable Cutlets.jpg",
    "category": "starters",
    "categoryLabel": "Starters",
    "veg": "veg",
    "rating": 4.2,
    "reviews": 76,
    "bestseller": false,
    "description": "Crispy, flavourful and irresistible — our Crispy Vegetable Cutlets is a guest favourite to kick off your meal."
  },
  {
    "slug": "chicken-pakoda",
    "name": "Chicken Pakoda",
    "price": 180,
    "img": "assets/images/starters/Chiken Pakoda.jpg",
    "category": "starters",
    "categoryLabel": "Starters",
    "veg": "nonveg",
    "rating": 4.3,
    "reviews": 26,
    "bestseller": false,
    "description": "Crispy, flavourful and irresistible — our Chicken Pakoda is a guest favourite to kick off your meal."
  },
  {
    "slug": "roasted-chicken",
    "name": "Roasted Chicken",
    "price": 160,
    "img": "assets/images/starters/Roasted-Chiken.jpg",
    "category": "starters",
    "categoryLabel": "Starters",
    "veg": "nonveg",
    "rating": 4.7,
    "reviews": 100,
    "bestseller": false,
    "description": "Crispy, flavourful and irresistible — our Roasted Chicken is a guest favourite to kick off your meal."
  },
  {
    "slug": "chicken-legs",
    "name": "Chicken Legs",
    "price": 180,
    "img": "assets/images/starters/Chiken-legs.jpg",
    "category": "starters",
    "categoryLabel": "Starters",
    "veg": "nonveg",
    "rating": 4.4,
    "reviews": 48,
    "bestseller": false,
    "description": "Crispy, flavourful and irresistible — our Chicken Legs is a guest favourite to kick off your meal."
  },
  {
    "slug": "green-salad",
    "name": "Green Salad",
    "price": 30,
    "img": "assets/images/salads/Green Salad.jpg",
    "category": "salads",
    "categoryLabel": "Salads & Soups",
    "veg": "veg",
    "rating": 4.3,
    "reviews": 61,
    "bestseller": false,
    "description": "Light, fresh and wholesome — Green Salad is tossed with quality ingredients for a refreshing start."
  },
  {
    "slug": "apple-carrot-salad",
    "name": "Apple Carrot Salad",
    "price": 100,
    "img": "assets/images/salads/Apple Carrot Salad.jpg",
    "category": "salads",
    "categoryLabel": "Salads & Soups",
    "veg": "veg",
    "rating": 4.6,
    "reviews": 102,
    "bestseller": false,
    "description": "A nourishing bowl of Apple Carrot Salad, made fresh to balance out your meal beautifully."
  },
  {
    "slug": "salad-papad",
    "name": "Salad Papad",
    "price": 30,
    "img": "assets/images/salads/Salad Papad.jpg",
    "category": "salads",
    "categoryLabel": "Salads & Soups",
    "veg": "veg",
    "rating": 4.4,
    "reviews": 71,
    "bestseller": false,
    "description": "Light, fresh and wholesome — Salad Papad is tossed with quality ingredients for a refreshing start."
  },
  {
    "slug": "mix-healthy-salad",
    "name": "Mix Healthy Salad",
    "price": 80,
    "img": "assets/images/salads/Mix Healthy Salad.jpg",
    "category": "salads",
    "categoryLabel": "Salads & Soups",
    "veg": "veg",
    "rating": 4.3,
    "reviews": 167,
    "bestseller": false,
    "description": "Light, fresh and wholesome — Mix Healthy Salad is tossed with quality ingredients for a refreshing start."
  },
  {
    "slug": "chicken-soup",
    "name": "Chicken Soup",
    "price": 140,
    "img": "assets/images/salads/Chiken Soup.jpg",
    "category": "salads",
    "categoryLabel": "Salads & Soups",
    "veg": "nonveg",
    "rating": 4.5,
    "reviews": 54,
    "bestseller": false,
    "description": "A nourishing bowl of Chicken Soup, made fresh to balance out your meal beautifully."
  },
  {
    "slug": "mushroom-soup",
    "name": "Mushroom Soup",
    "price": 160,
    "img": "assets/images/salads/Mashroom Soup.jpg",
    "category": "salads",
    "categoryLabel": "Salads & Soups",
    "veg": "veg",
    "rating": 4.5,
    "reviews": 69,
    "bestseller": false,
    "description": "Light, fresh and wholesome — Mushroom Soup is tossed with quality ingredients for a refreshing start."
  },
  {
    "slug": "mix-spicy-soup",
    "name": "Mix Spicy Soup",
    "price": 80,
    "img": "assets/images/salads/Mix Spicy Soup.jpg",
    "category": "salads",
    "categoryLabel": "Salads & Soups",
    "veg": "veg",
    "rating": 4.5,
    "reviews": 95,
    "bestseller": false,
    "description": "Light, fresh and wholesome — Mix Spicy Soup is tossed with quality ingredients for a refreshing start."
  },
  {
    "slug": "noodles-soup",
    "name": "Noodles Soup",
    "price": 100,
    "img": "assets/images/salads/Noodles Soup.jpg",
    "category": "salads",
    "categoryLabel": "Salads & Soups",
    "veg": "veg",
    "rating": 4.8,
    "reviews": 148,
    "bestseller": false,
    "description": "A nourishing bowl of Noodles Soup, made fresh to balance out your meal beautifully."
  },
  {
    "slug": "aloo-gobi",
    "name": "Aloo Gobi",
    "price": 60,
    "img": "assets/images/main(veg)/Aloo Gobi.jpg",
    "category": "main-veg",
    "categoryLabel": "Main Course (Veg)",
    "veg": "veg",
    "rating": 4.4,
    "reviews": 80,
    "bestseller": false,
    "description": "Aloo Gobi — a comforting, flavour-packed vegetarian main course made the traditional way."
  },
  {
    "slug": "bhindi-salan",
    "name": "Bhindi Salan",
    "price": 80,
    "img": "assets/images/main(veg)/Bhindi Salan.jpg",
    "category": "main-veg",
    "categoryLabel": "Main Course (Veg)",
    "veg": "veg",
    "rating": 4.1,
    "reviews": 154,
    "bestseller": false,
    "description": "Bhindi Salan — a comforting, flavour-packed vegetarian main course made the traditional way."
  },
  {
    "slug": "moong-dal-tadka",
    "name": "Moong Dal Tadka",
    "price": 100,
    "img": "assets/images/main(veg)/Moong Dal Tadka.jpg",
    "category": "main-veg",
    "categoryLabel": "Main Course (Veg)",
    "veg": "veg",
    "rating": 4.4,
    "reviews": 173,
    "bestseller": false,
    "description": "A rich, home-style preparation of Moong Dal Tadka, simmered with authentic spices for pure vegetarian delight."
  },
  {
    "slug": "paneer-makkhan",
    "name": "Paneer Makkhan",
    "price": 150,
    "img": "assets/images/main(veg)/Paneer Makkhan.jpg",
    "category": "main-veg",
    "categoryLabel": "Main Course (Veg)",
    "veg": "veg",
    "rating": 4.4,
    "reviews": 25,
    "bestseller": false,
    "description": "A rich, home-style preparation of Paneer Makkhan, simmered with authentic spices for pure vegetarian delight."
  },
  {
    "slug": "spicy-baghare-baingan",
    "name": "Spicy Baghare Baingan",
    "price": 80,
    "img": "assets/images/main(veg)/Spicy Baghare Baingan.jpg",
    "category": "main-veg",
    "categoryLabel": "Main Course (Veg)",
    "veg": "veg",
    "rating": 4.6,
    "reviews": 270,
    "bestseller": false,
    "description": "Spicy Baghare Baingan — a comforting, flavour-packed vegetarian main course made the traditional way."
  },
  {
    "slug": "dal-methi",
    "name": "Dal Methi",
    "price": 70,
    "img": "assets/images/main(veg)/Dal-Methi.jpg",
    "category": "main-veg",
    "categoryLabel": "Main Course (Veg)",
    "veg": "veg",
    "rating": 4.2,
    "reviews": 160,
    "bestseller": false,
    "description": "Dal Methi — a comforting, flavour-packed vegetarian main course made the traditional way."
  },
  {
    "slug": "vegetable-dum-biryani",
    "name": "Vegetable Dum Biryani",
    "price": 160,
    "img": "assets/images/main(veg)/Vegetable Dum Biryani.jpg",
    "category": "main-veg",
    "categoryLabel": "Main Course (Veg)",
    "veg": "veg",
    "rating": 4.3,
    "reviews": 76,
    "bestseller": false,
    "description": "Vegetable Dum Biryani — a comforting, flavour-packed vegetarian main course made the traditional way."
  },
  {
    "slug": "corn-palak",
    "name": "Corn Palak",
    "price": 100,
    "img": "assets/images/main(veg)/Corn Palak.jpg",
    "category": "main-veg",
    "categoryLabel": "Main Course (Veg)",
    "veg": "veg",
    "rating": 4.7,
    "reviews": 238,
    "bestseller": false,
    "description": "Corn Palak — a comforting, flavour-packed vegetarian main course made the traditional way."
  },
  {
    "slug": "hyd-chicken-biryani",
    "name": "HYD Chicken Biryani",
    "price": 250,
    "img": "assets/images/main(non-veg)/Hyderabadi Chicken Biryani.jpg",
    "category": "main-nonveg",
    "categoryLabel": "Main Course (Non-Veg)",
    "veg": "nonveg",
    "rating": 4.7,
    "reviews": 32,
    "bestseller": true,
    "description": "A signature non-vegetarian main course — HYD Chicken Biryani, prepared with authentic spices and generous portions."
  },
  {
    "slug": "tandoori-chicken",
    "name": "Tandoori Chicken",
    "price": 360,
    "img": "assets/images/main(non-veg)/Tandoori Chicken.jpg",
    "category": "main-nonveg",
    "categoryLabel": "Main Course (Non-Veg)",
    "veg": "nonveg",
    "rating": 4.2,
    "reviews": 199,
    "bestseller": true,
    "description": "Slow-cooked to perfection, our Tandoori Chicken delivers rich, royal flavours in every bite."
  },
  {
    "slug": "chicken-karahi",
    "name": "Chicken Karahi",
    "price": 175,
    "img": "assets/images/main(non-veg)/Chicken Karahi.jpg",
    "category": "main-nonveg",
    "categoryLabel": "Main Course (Non-Veg)",
    "veg": "nonveg",
    "rating": 4.0,
    "reviews": 174,
    "bestseller": false,
    "description": "A signature non-vegetarian main course — Chicken Karahi, prepared with authentic spices and generous portions."
  },
  {
    "slug": "creamy-garlic-chicken",
    "name": "Creamy Garlic Chicken",
    "price": 180,
    "img": "assets/images/main(non-veg)/Creamy Garlic Chicken.jpg",
    "category": "main-nonveg",
    "categoryLabel": "Main Course (Non-Veg)",
    "veg": "nonveg",
    "rating": 4.4,
    "reviews": 235,
    "bestseller": false,
    "description": "Slow-cooked to perfection, our Creamy Garlic Chicken delivers rich, royal flavours in every bite."
  },
  {
    "slug": "crispy-spicy-fried-fish",
    "name": "Crispy Spicy Fried Fish",
    "price": 260,
    "img": "assets/images/main(non-veg)/Crispy Spicy Fried Fish.jpg",
    "category": "main-nonveg",
    "categoryLabel": "Main Course (Non-Veg)",
    "veg": "nonveg",
    "rating": 4.1,
    "reviews": 162,
    "bestseller": false,
    "description": "A signature non-vegetarian main course — Crispy Spicy Fried Fish, prepared with authentic spices and generous portions."
  },
  {
    "slug": "spicy-mutton",
    "name": "Spicy Mutton",
    "price": 160,
    "img": "assets/images/main(non-veg)/Spicy Mutton.jpg",
    "category": "main-nonveg",
    "categoryLabel": "Main Course (Non-Veg)",
    "veg": "nonveg",
    "rating": 4.5,
    "reviews": 236,
    "bestseller": false,
    "description": "A signature non-vegetarian main course — Spicy Mutton, prepared with authentic spices and generous portions."
  },
  {
    "slug": "chicken-hyderabadi",
    "name": "Chicken Hyderabadi",
    "price": 190,
    "img": "assets/images/main(non-veg)/Chicken Hyderabadi.jpg",
    "category": "main-nonveg",
    "categoryLabel": "Main Course (Non-Veg)",
    "veg": "nonveg",
    "rating": 4.6,
    "reviews": 123,
    "bestseller": false,
    "description": "Slow-cooked to perfection, our Chicken Hyderabadi delivers rich, royal flavours in every bite."
  },
  {
    "slug": "bhuna-keema",
    "name": "Bhuna Keema",
    "price": 200,
    "img": "assets/images/main(non-veg)/Bhuna Keema.jpg",
    "category": "main-nonveg",
    "categoryLabel": "Main Course (Non-Veg)",
    "veg": "nonveg",
    "rating": 4.6,
    "reviews": 104,
    "bestseller": false,
    "description": "A signature non-vegetarian main course — Bhuna Keema, prepared with authentic spices and generous portions."
  },
  {
    "slug": "chicken-biryani",
    "name": "Chicken Biryani",
    "price": 280,
    "img": "assets/images/rice & biryani/Chicken Biryani.jpg",
    "category": "rice",
    "categoryLabel": "Rice & Biryani",
    "veg": "nonveg",
    "rating": 4.0,
    "reviews": 132,
    "bestseller": true,
    "description": "Our Chicken Biryani is prepared the traditional way for that authentic, aromatic experience."
  },
  {
    "slug": "paneer-biryani",
    "name": "Paneer Biryani",
    "price": 260,
    "img": "assets/images/rice & biryani/Paneer Biryani.jpg",
    "category": "rice",
    "categoryLabel": "Rice & Biryani",
    "veg": "veg",
    "rating": 4.1,
    "reviews": 241,
    "bestseller": false,
    "description": "Fragrant, perfectly cooked Paneer Biryani layered with authentic spices — a meal in itself."
  },
  {
    "slug": "veg-biryani",
    "name": "Veg Biryani",
    "price": 240,
    "img": "assets/images/rice & biryani/Veg Biryani.jpg",
    "category": "rice",
    "categoryLabel": "Rice & Biryani",
    "veg": "veg",
    "rating": 4.0,
    "reviews": 224,
    "bestseller": false,
    "description": "Our Veg Biryani is prepared the traditional way for that authentic, aromatic experience."
  },
  {
    "slug": "hyderabadi-mutton-biryani",
    "name": "Hyderabadi Mutton Biryani",
    "price": 280,
    "img": "assets/images/rice & biryani/Hyderabadi Mutton Biryani.jpg",
    "category": "rice",
    "categoryLabel": "Rice & Biryani",
    "veg": "nonveg",
    "rating": 4.2,
    "reviews": 53,
    "bestseller": false,
    "description": "Fragrant, perfectly cooked Hyderabadi Mutton Biryani layered with authentic spices — a meal in itself."
  },
  {
    "slug": "jeera-rice",
    "name": "Jeera Rice",
    "price": 160,
    "img": "assets/images/rice & biryani/Jeera Rice.jpg",
    "category": "rice",
    "categoryLabel": "Rice & Biryani",
    "veg": "veg",
    "rating": 4.8,
    "reviews": 34,
    "bestseller": false,
    "description": "Our Jeera Rice is prepared the traditional way for that authentic, aromatic experience."
  },
  {
    "slug": "lemon-rice",
    "name": "Lemon Rice",
    "price": 180,
    "img": "assets/images/rice & biryani/Lemon Rice.jpg",
    "category": "rice",
    "categoryLabel": "Rice & Biryani",
    "veg": "veg",
    "rating": 4.7,
    "reviews": 249,
    "bestseller": false,
    "description": "Fragrant, perfectly cooked Lemon Rice layered with authentic spices — a meal in itself."
  },
  {
    "slug": "fried-rice",
    "name": "Fried Rice",
    "price": 190,
    "img": "assets/images/rice & biryani/Fried Rice.jpg",
    "category": "rice",
    "categoryLabel": "Rice & Biryani",
    "veg": "veg",
    "rating": 4.2,
    "reviews": 133,
    "bestseller": false,
    "description": "Fragrant, perfectly cooked Fried Rice layered with authentic spices — a meal in itself."
  },
  {
    "slug": "veg-pulav",
    "name": "Veg Pulav",
    "price": 160,
    "img": "assets/images/rice & biryani/Veg Pulav.jpg",
    "category": "rice",
    "categoryLabel": "Rice & Biryani",
    "veg": "veg",
    "rating": 4.0,
    "reviews": 242,
    "bestseller": false,
    "description": "Our Veg Pulav is prepared the traditional way for that authentic, aromatic experience."
  },
  {
    "slug": "hamburger",
    "name": "Hamburger",
    "price": 140,
    "img": "assets/images/street, junk & more/Hamburger.jpg",
    "category": "street",
    "categoryLabel": "Street & Junk Foods",
    "veg": "nonveg",
    "rating": 4.5,
    "reviews": 166,
    "bestseller": false,
    "description": "Classic street-style Hamburger, prepared with a Fly Restaurant twist."
  },
  {
    "slug": "hot-dogs",
    "name": "Hot Dogs",
    "price": 160,
    "img": "assets/images/street, junk & more/Hot Dogs.jpg",
    "category": "street",
    "categoryLabel": "Street & Junk Foods",
    "veg": "nonveg",
    "rating": 4.2,
    "reviews": 273,
    "bestseller": false,
    "description": "A quick, satisfying favourite — Hot Dogs, made fresh to order."
  },
  {
    "slug": "schezwan-vada-pav",
    "name": "Schezwan Vada Pav",
    "price": 60,
    "img": "assets/images/street, junk & more/Shezvaan Vada Paav.jpg",
    "category": "street",
    "categoryLabel": "Street & Junk Foods",
    "veg": "veg",
    "rating": 4.1,
    "reviews": 40,
    "bestseller": true,
    "description": "Classic street-style Schezwan Vada Pav, prepared with a Fly Restaurant twist."
  },
  {
    "slug": "tacos",
    "name": "Tacos",
    "price": 130,
    "img": "assets/images/street, junk & more/Tacos.jpg",
    "category": "street",
    "categoryLabel": "Street & Junk Foods",
    "veg": "veg",
    "rating": 4.7,
    "reviews": 95,
    "bestseller": false,
    "description": "A quick, satisfying favourite — Tacos, made fresh to order."
  },
  {
    "slug": "pizza",
    "name": "Pizza",
    "price": 180,
    "img": "assets/images/street, junk & more/Pizza.jpg",
    "category": "street",
    "categoryLabel": "Street & Junk Foods",
    "veg": "veg",
    "rating": 4.2,
    "reviews": 45,
    "bestseller": false,
    "description": "A quick, satisfying favourite — Pizza, made fresh to order."
  },
  {
    "slug": "egg-puffs",
    "name": "Egg Puffs",
    "price": 50,
    "img": "assets/images/street, junk & more/Egg Puffs.jpg",
    "category": "street",
    "categoryLabel": "Street & Junk Foods",
    "veg": "egg",
    "rating": 4.6,
    "reviews": 252,
    "bestseller": false,
    "description": "Classic street-style Egg Puffs, prepared with a Fly Restaurant twist."
  },
  {
    "slug": "sandwich",
    "name": "Sandwich",
    "price": 100,
    "img": "assets/images/street, junk & more/Sandwich.jpg",
    "category": "street",
    "categoryLabel": "Street & Junk Foods",
    "veg": "veg",
    "rating": 4.3,
    "reviews": 193,
    "bestseller": false,
    "description": "A quick, satisfying favourite — Sandwich, made fresh to order."
  },
  {
    "slug": "naan-bread",
    "name": "Naan Bread",
    "price": 60,
    "img": "assets/images/street, junk & more/Naan Bread.jpg",
    "category": "street",
    "categoryLabel": "Street & Junk Foods",
    "veg": "veg",
    "rating": 4.8,
    "reviews": 142,
    "bestseller": false,
    "description": "Classic street-style Naan Bread, prepared with a Fly Restaurant twist."
  },
  {
    "slug": "hakka-noodles",
    "name": "Hakka Noodles",
    "price": 120,
    "img": "assets/images/chinese & fast foods/Hakka Noodles.jpg",
    "category": "chinese",
    "categoryLabel": "Chinese & Fast Foods",
    "veg": "veg",
    "rating": 4.1,
    "reviews": 161,
    "bestseller": true,
    "description": "Wok-tossed and full of bold flavour — our Hakka Noodles is a Chinese menu favourite."
  },
  {
    "slug": "chicken-manchurian",
    "name": "Chicken Manchurian",
    "price": 160,
    "img": "assets/images/chinese & fast foods/Chicken Manchurian.jpg",
    "category": "chinese",
    "categoryLabel": "Chinese & Fast Foods",
    "veg": "nonveg",
    "rating": 4.0,
    "reviews": 247,
    "bestseller": true,
    "description": "Wok-tossed and full of bold flavour — our Chicken Manchurian is a Chinese menu favourite."
  },
  {
    "slug": "spicy-momos",
    "name": "Spicy Momos",
    "price": 140,
    "img": "assets/images/chinese & fast foods/Spicy Momos.jpg",
    "category": "chinese",
    "categoryLabel": "Chinese & Fast Foods",
    "veg": "veg",
    "rating": 4.2,
    "reviews": 206,
    "bestseller": false,
    "description": "Spicy Momos, prepared fresh with authentic Indo-Chinese spices and a satisfying kick."
  },
  {
    "slug": "french-fries",
    "name": "French Fries",
    "price": 110,
    "img": "assets/images/chinese & fast foods/French Fries.jpg",
    "category": "chinese",
    "categoryLabel": "Chinese & Fast Foods",
    "veg": "veg",
    "rating": 4.1,
    "reviews": 187,
    "bestseller": false,
    "description": "Wok-tossed and full of bold flavour — our French Fries is a Chinese menu favourite."
  },
  {
    "slug": "schezwan-spicy-noodles",
    "name": "Schezwan Spicy Noodles",
    "price": 130,
    "img": "assets/images/chinese & fast foods/Schezwan Spicy Noodles.jpg",
    "category": "chinese",
    "categoryLabel": "Chinese & Fast Foods",
    "veg": "veg",
    "rating": 4.3,
    "reviews": 46,
    "bestseller": false,
    "description": "Schezwan Spicy Noodles, prepared fresh with authentic Indo-Chinese spices and a satisfying kick."
  },
  {
    "slug": "hot-crispy-chilly-paneer",
    "name": "Hot Crispy Chilly Paneer",
    "price": 100,
    "img": "assets/images/chinese & fast foods/Hot Crispy Chilly Paneer.jpg",
    "category": "chinese",
    "categoryLabel": "Chinese & Fast Foods",
    "veg": "veg",
    "rating": 4.5,
    "reviews": 62,
    "bestseller": false,
    "description": "Hot Crispy Chilly Paneer, prepared fresh with authentic Indo-Chinese spices and a satisfying kick."
  },
  {
    "slug": "chicken-65",
    "name": "Chicken 65",
    "price": 160,
    "img": "assets/images/chinese & fast foods/Chicken 65.jpg",
    "category": "chinese",
    "categoryLabel": "Chinese & Fast Foods",
    "veg": "nonveg",
    "rating": 4.7,
    "reviews": 218,
    "bestseller": false,
    "description": "Chicken 65, prepared fresh with authentic Indo-Chinese spices and a satisfying kick."
  },
  {
    "slug": "spring-rolls",
    "name": "Spring Rolls",
    "price": 160,
    "img": "assets/images/chinese & fast foods/Spring Rolls.jpg",
    "category": "chinese",
    "categoryLabel": "Chinese & Fast Foods",
    "veg": "veg",
    "rating": 4.1,
    "reviews": 266,
    "bestseller": false,
    "description": "Spring Rolls, prepared fresh with authentic Indo-Chinese spices and a satisfying kick."
  },
  {
    "slug": "gulab-jamuns",
    "name": "Gulab Jamuns",
    "price": 30,
    "img": "assets/images/desserts/Gulab Jamuns.jpg",
    "category": "desserts",
    "categoryLabel": "Desserts",
    "veg": "veg",
    "rating": 4.3,
    "reviews": 159,
    "bestseller": true,
    "description": "A sweet ending to your meal — Gulab Jamuns, made to satisfy every craving."
  },
  {
    "slug": "soft-rasgulla",
    "name": "Soft Rasgulla",
    "price": 40,
    "img": "assets/images/desserts/Soft Rasgulla.jpg",
    "category": "desserts",
    "categoryLabel": "Desserts",
    "veg": "veg",
    "rating": 4.2,
    "reviews": 30,
    "bestseller": false,
    "description": "Indulge in our Soft Rasgulla, crafted to be the perfect finishing touch."
  },
  {
    "slug": "soft-balushahi",
    "name": "Soft Balushahi",
    "price": 30,
    "img": "assets/images/desserts/Soft Balushahi.jpg",
    "category": "desserts",
    "categoryLabel": "Desserts",
    "veg": "veg",
    "rating": 4.5,
    "reviews": 83,
    "bestseller": false,
    "description": "A sweet ending to your meal — Soft Balushahi, made to satisfy every craving."
  },
  {
    "slug": "rasmalai",
    "name": "Rasmalai",
    "price": 100,
    "img": "assets/images/desserts/Rasmalai.jpg",
    "category": "desserts",
    "categoryLabel": "Desserts",
    "veg": "veg",
    "rating": 4.2,
    "reviews": 34,
    "bestseller": true,
    "description": "Indulge in our Rasmalai, crafted to be the perfect finishing touch."
  },
  {
    "slug": "chocolate-heaven-delight",
    "name": "Chocolate Heaven Delight",
    "price": 120,
    "img": "assets/images/desserts/Chocolate Heaven Delight.jpg",
    "category": "desserts",
    "categoryLabel": "Desserts",
    "veg": "veg",
    "rating": 4.5,
    "reviews": 228,
    "bestseller": false,
    "description": "Indulge in our Chocolate Heaven Delight, crafted to be the perfect finishing touch."
  },
  {
    "slug": "dreamy-ice-cream-delight",
    "name": "Dreamy Ice Cream Delight",
    "price": 140,
    "img": "assets/images/desserts/Dreamy Ice Cream Delight.jpg",
    "category": "desserts",
    "categoryLabel": "Desserts",
    "veg": "veg",
    "rating": 4.8,
    "reviews": 167,
    "bestseller": false,
    "description": "A sweet ending to your meal — Dreamy Ice Cream Delight, made to satisfy every craving."
  },
  {
    "slug": "motichur-laddu",
    "name": "Motichur Laddu",
    "price": 80,
    "img": "assets/images/desserts/Motichure Laddu.jpg",
    "category": "desserts",
    "categoryLabel": "Desserts",
    "veg": "veg",
    "rating": 4.8,
    "reviews": 207,
    "bestseller": false,
    "description": "A sweet ending to your meal — Motichur Laddu, made to satisfy every craving."
  },
  {
    "slug": "lauki-kheer",
    "name": "Lauki Kheer",
    "price": 100,
    "img": "assets/images/desserts/Lauki kheer.jpg",
    "category": "desserts",
    "categoryLabel": "Desserts",
    "veg": "veg",
    "rating": 4.6,
    "reviews": 160,
    "bestseller": false,
    "description": "Indulge in our Lauki Kheer, crafted to be the perfect finishing touch."
  },
  {
    "slug": "cold-coffee",
    "name": "Cold Coffee",
    "price": 120,
    "img": "assets/images/beverages/Cold Coffee.jpg",
    "category": "beverages",
    "categoryLabel": "Beverages",
    "veg": "veg",
    "rating": 4.7,
    "reviews": 215,
    "bestseller": true,
    "description": "Refresh and recharge with our Cold Coffee — the perfect companion to your meal."
  },
  {
    "slug": "hot-coffee",
    "name": "Hot Coffee",
    "price": 80,
    "img": "assets/images/beverages/Hot Coffee.jpg",
    "category": "beverages",
    "categoryLabel": "Beverages",
    "veg": "veg",
    "rating": 4.8,
    "reviews": 110,
    "bestseller": false,
    "description": "Cool, refreshing Hot Coffee, served chilled just the way you like it."
  },
  {
    "slug": "masala-tea",
    "name": "Masala Tea",
    "price": 40,
    "img": "assets/images/beverages/Masala Tea.jpg",
    "category": "beverages",
    "categoryLabel": "Beverages",
    "veg": "veg",
    "rating": 4.6,
    "reviews": 170,
    "bestseller": false,
    "description": "Cool, refreshing Masala Tea, served chilled just the way you like it."
  },
  {
    "slug": "leaf-green-tea",
    "name": "Leaf Green Tea",
    "price": 50,
    "img": "assets/images/beverages/Leaf Green Tea.jpg",
    "category": "beverages",
    "categoryLabel": "Beverages",
    "veg": "veg",
    "rating": 4.1,
    "reviews": 153,
    "bestseller": false,
    "description": "Refresh and recharge with our Leaf Green Tea — the perfect companion to your meal."
  },
  {
    "slug": "coca-cola",
    "name": "Coca Cola",
    "price": 30,
    "img": "assets/images/beverages/Coca Cola.jpg",
    "category": "beverages",
    "categoryLabel": "Beverages",
    "veg": "veg",
    "rating": 4.6,
    "reviews": 262,
    "bestseller": false,
    "description": "Cool, refreshing Coca Cola, served chilled just the way you like it."
  },
  {
    "slug": "sprite",
    "name": "Sprite",
    "price": 30,
    "img": "assets/images/beverages/Sprite.jpg",
    "category": "beverages",
    "categoryLabel": "Beverages",
    "veg": "veg",
    "rating": 4.5,
    "reviews": 268,
    "bestseller": false,
    "description": "Cool, refreshing Sprite, served chilled just the way you like it."
  },
  {
    "slug": "jal-jeera",
    "name": "Jal Jeera",
    "price": 20,
    "img": "assets/images/beverages/Jal Jeera.jpg",
    "category": "beverages",
    "categoryLabel": "Beverages",
    "veg": "veg",
    "rating": 4.1,
    "reviews": 117,
    "bestseller": false,
    "description": "Refresh and recharge with our Jal Jeera — the perfect companion to your meal."
  },
  {
    "slug": "lemon-juice",
    "name": "Lemon Juice",
    "price": 50,
    "img": "assets/images/beverages/Lemon Juice.jpg",
    "category": "beverages",
    "categoryLabel": "Beverages",
    "veg": "veg",
    "rating": 4.0,
    "reviews": 106,
    "bestseller": false,
    "description": "Cool, refreshing Lemon Juice, served chilled just the way you like it."
  },
  {
    "slug": "mixed-fruit-juice",
    "name": "Mixed Fruit Juice",
    "price": 140,
    "img": "assets/images/beverages/Mixed Fruit Juice.jpg",
    "category": "beverages",
    "categoryLabel": "Beverages",
    "veg": "veg",
    "rating": 4.4,
    "reviews": 202,
    "bestseller": false,
    "description": "Cool, refreshing Mixed Fruit Juice, served chilled just the way you like it."
  },
  {
    "slug": "sugarcane-juice",
    "name": "Sugarcane Juice",
    "price": 30,
    "img": "assets/images/beverages/Sugarcane Juice.jpg",
    "category": "beverages",
    "categoryLabel": "Beverages",
    "veg": "veg",
    "rating": 4.4,
    "reviews": 247,
    "bestseller": false,
    "description": "Refresh and recharge with our Sugarcane Juice — the perfect companion to your meal."
  },
  {
    "slug": "roohafza",
    "name": "Roohafza",
    "price": 60,
    "img": "assets/images/beverages/Roohafza.jpg",
    "category": "beverages",
    "categoryLabel": "Beverages",
    "veg": "veg",
    "rating": 4.5,
    "reviews": 217,
    "bestseller": false,
    "description": "Refresh and recharge with our Roohafza — the perfect companion to your meal."
  },
  {
    "slug": "falooda",
    "name": "Falooda",
    "price": 100,
    "img": "assets/images/beverages/Falooda.jpg",
    "category": "beverages",
    "categoryLabel": "Beverages",
    "veg": "veg",
    "rating": 4.2,
    "reviews": 175,
    "bestseller": false,
    "description": "Refresh and recharge with our Falooda — the perfect companion to your meal."
  }
];
